services:
  backend_python:
    build:
      context: ./backend_python
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend_python/src:/app/src
    environment:
      - RUNBOOKS_TESTING_DB_PATH=/app/data/runbooks_testing.db
    # volumes for persistent sqlite
    # - ./data:/app/data

  backend_go:
    build:
      context: ./backend_go
      target: prod
    ports:
      - "8080:8080"

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend_python
